ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/EthPeer.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/messages/GetBlockHeadersMessage.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/tasks/GetHeadersFromPeerByHashTask.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/tasks/GetHeadersFromPeerByNumberTask.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/EthPeerTest.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/EthProtocolManagerTest.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/messages/GetBlockHeadersMessageTest.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/tasks/DetermineCommonAncestorTaskTest.java
Remove `RLPUtils` from `GetBlockHeadersMessage` as part of the work to remove `RLPUtils` altogether.  Also reworked the parameter order for the `create` methods to match the ordering used when rlp-encoding this message.
**Note:** Re-creating this PR after open-sourcing issues caused my previous PR to be closed: https://github.com/PegaSysEng/pantheon/pull/155
=> [NC-1561] Remove RLPUtils from GetBlockHeadersMessage

ethereum/rlp/src/jmh/java/tech/pegasys/pantheon/ethereum/rlp/RLPBench.java, ethereum/rlp/src/main/java/tech/pegasys/pantheon/ethereum/rlp/RLP.java, ethereum/rlp/src/main/java/tech/pegasys/pantheon/ethereum/rlp/RLPDecodingHelpers.java, ethereum/rlp/src/test/java/tech/pegasys/pantheon/ethereum/rlp/BytesValueRLPInputTest.java, ethereum/rlp/src/test/java/tech/pegasys/pantheon/ethereum/rlp/BytesValueRLPOutputTest.java, ethereum/rlp/src/test/java/tech/pegasys/pantheon/ethereum/rlp/InvalidRLPRefTest.java, ethereum/rlp/src/test/java/tech/pegasys/pantheon/ethereum/rlp/RLPRefTest.java, ethereum/rlp/src/test/java/tech/pegasys/pantheon/ethereum/rlp/RLPTest.java, ethereum/rlp/src/test/java/tech/pegasys/pantheon/ethereum/rlp/util/RLPTestUtil.java
* Add some additional RLP tests
* Move generic encode / decode RLP methods into a test utility as these methods should never be used in production  
* Rework some RLP error messages for clarity
* Fix an issue where an `ArithmeticException` was being thrown by wrapping it in a more meaningful `RLPException`
* Migrate tests to use AssertJ test utilities
=> Add additional RLP tests

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryAgent.java
This is somewhat of a drive-by amelioration. I was going to test it but this is actually kind of hard to test, and I didn't want to spend a lot of time trying to make a good test for this, so I almost didn't change it- but anyway- I in fact did test it once, by making the method from `private` to `public` so I know that it behaves as expected.
=> [MINOR] Render handler exception to System.err instead of .out

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/ApiHandler.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyP2PNetwork.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/wire/messages/DisconnectMessage.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/NettyP2PNetworkTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/wire/messages/DisconnectMessageTest.java
As an alternative to https://github.com/PegaSysEng/pantheon/pull/354, this PR handles wire disconnect messages with no explicit reason by adding a new UNKNOWN `DisconnectReason` value.  It also includes the following changes:
* Add tests for parsing and constructing `DisconnectMessage`'s
* Send an empty reason when we disconnect from blacklisted peers
=> Add an UNKNOWN DisconnectReason

consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/jsonrpc/methods/IbftGetValidatorsByBlockHash.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/jsonrpc/methods/IbftGetValidatorsByBlockNumber.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/jsonrpc/methods/IbftGetValidatorsByBlockHashTest.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/jsonrpc/methods/IbftGetValidatorsByBlockNumberTest.java
The ibftGetValidatorsByBlockNumber and ibftGetValidatorsByBlockHash
both returned a list of Addresses, whichi when translated back into
JSON RPC responses, results in an incorrect 'shape'.
These RPC calls should (and now do) return a list of strings.
=> Ibft Validator RPCs to return list of strings

consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/jsonrpc/IbftJsonRpcMethodsFactory.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/jsonrpc/methods/IbftGetValidatorsByBlockHash.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/jsonrpc/methods/IbftGetValidatorsByBlockNumber.java
The JSON RPC handler was pre-existing, but was not "wired" into the JSON RPC factory, and as such, was not being recognised as an available JSON RPC method.
This commit updates the Factory such that the RPC will be available externally.
=> IbftGetValidatorsByBlockHash added to json factory

consensus/ibft/src/integration-test/java/tech/pegasys/pantheon/consensus/ibft/support/RoundSpecificPeers.java, consensus/ibft/src/integration-test/java/tech/pegasys/pantheon/consensus/ibft/support/ValidatorPeer.java, consensus/ibft/src/integration-test/java/tech/pegasys/pantheon/consensus/ibft/tests/GossipTest.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/IbftGossip.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/messagedata/CommitMessageData.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/messagedata/NewRoundMessageData.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/messagedata/PrepareMessageData.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/messagedata/ProposalMessageData.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/messagedata/RoundChangeMessageData.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/messagewrappers/Commit.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/messagewrappers/IbftMessage.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/messagewrappers/NewRound.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/messagewrappers/Prepare.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/messagewrappers/Proposal.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/messagewrappers/RoundChange.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/network/IbftMessageTransmitter.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/payload/Authored.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/payload/Payload.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/payload/RoundSpecific.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/payload/SignedData.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/statemachine/IbftController.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/IbftGossipTest.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/TestHelpers.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/messagedata/CommitMessageTest.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/messagedata/NewRoundMessageTest.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/messagedata/PrepareMessageTest.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/messagedata/ProposalMessageTest.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/messagedata/RoundChangeMessageTest.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/statemachine/IbftControllerTest.java
As future IBFT message will require only subsets of the data to be signed,
the message structures need to be modified such taht the signed-data
aspects can be a component of the message (Rather than the whole
message).
This change starts this process by having a "flat" message which allows
clients to query the required round, and author of the message.
=> Create wrapper types for Ibft Signed messages

consensus/ibftlegacy/src/main/java/tech/pegasys/pantheon/consensus/ibftlegacy/protocol/Istanbul64ProtocolManager.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/EthProtocolManager.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/EthScheduler.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/SynchronizerConfiguration.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/DeterministicEthScheduler.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/EthProtocolManagerTest.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/EthSchedulerShutdownTest.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/MockEthTask.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/TestNode.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/CliquePantheonController.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/IbftLegacyPantheonController.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/IbftPantheonController.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/MainnetPantheonController.java
Add the services thread pool and a computation thread pool to the
EthScheduler.
* Services are long running, sequential, and infrequently start tasks
such as Full Sync and Fast Sync.
* Computations are short and high CPU intensity tasks such as ECDSA
signature extractions and POW validation.  The intent is that each
runnable represents one such extraction and the extractions from a
block are saturated across available processing power.  These
computations should have zero dependencies outside their object and
thread.
=> EthScheduler additions

consensus/ibft/src/integration-test/java/tech/pegasys/pantheon/consensus/ibft/support/TestContextBuilder.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/statemachine/IbftRoundFactory.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/IbftPantheonController.java
The IbftRoundFactory creates a MessageValidator for use within the
newly created round, however it does this bypassing the established
factory classes (MessageValidatorFactory).
This commit updates the IbftRoundFactory to use the correct API for
creating the message validator.
=> Rework IbftRoundFactory

consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/statemachine/IbftBlockHeightManager.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/statemachine/IbftBlockHeightManagerFactory.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/validation/MessageValidatorFactory.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/statemachine/IbftBlockHeightManagerTest.java
With a prior change swapping header validation for block
validation in the IBFT messages, the necessity to pass in the block
header was removed - though the code remained.
This change simplifies the MessageValidatorFactory interface to only
take the chain height (rather than the full parent header).
=> Rework Ibft's MessageValidatorFactory

ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/WorldStateDownloader.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/WorldStateDownloaderTest.java, services/queue/src/main/java/tech/pegasys/pantheon/services/queue/BytesTaskQueueAdapter.java, services/queue/src/main/java/tech/pegasys/pantheon/services/queue/InMemoryTaskQueue.java, services/queue/src/main/java/tech/pegasys/pantheon/services/queue/RocksDbTaskQueue.java, services/queue/src/main/java/tech/pegasys/pantheon/services/queue/TaskQueue.java, services/queue/src/test/java/tech/pegasys/pantheon/services/queue/AbstractTaskQueueTest.java
Implement world state download cancellation functionality.  On cancellation, the `WorldStateDownloader` will cancel any pending network tasks and clear its task queue.  Also made a few other small changes: 
- ~Removed the `status` tracking from the downloader in favor of using the future as a signal on the status~.  
- Modified the downloader to return an exceptional result if `run` is called on an already running instance.
=> [PAN-2196] Implement world state cancel

pantheon/src/main/java/tech/pegasys/pantheon/cli/DefaultCommandValues.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/StandaloneCommand.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
Under docker its convention that we default the location to a more root centric location and disable the command line option. --permission-config-file slipped through.
=> [MINOR] permission config file location and option under docker

Jenkinsfile.benchmark
Make rinkby the benchmark chain.  Ropsten is too fragmented.
=> Make rinkeby the benchmark chain. 

pantheon/src/test/java/tech/pegasys/pantheon/RunnerTest.java
[PAN-2369] RunnerTest fail on Windows due to network startup timing issue
- Forces RunnerTest to wait for the P2PNetwork to start and actually configure it's ports before asking for them.
- Re-Enables RunnerTest.fullSyncFromGenesis()
- Re-Enables RunnerTest.fastSyncFromGenesis()
[PAN-2369]
[PAN-2369]: https://pegasys1.atlassian.net/browse/PAN-2369
[PAN-2369]: https://pegasys1.atlassian.net/browse/PAN-2369
=> [PAN-2369] RunnerTest fail on Windows due to network startup timing issue

ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcMethodsFactory.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/RpcModules.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/RpcModulesTest.java
rpc_module enumerates the modules exposed to RPC.  This allows the
`geth attach` geth javascript console to attach to Pantheon and use the
json-rpc APIs that pantheon and geth share.
=> [minor] add rpc_modules json-rpc

ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/task/AbstractPipelinedTask.java
Don't log expected failures as errors.
=> Don't log expected failures as errors

ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/WorldStateDownloaderTest.java
WorldStateDownloaderTest can get in an infinite loop.  Add a timeout rule.
=> Timeout long test

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryAgent.java
Lower the log level of discovery connections to unreachable networks,
such as a box without IPv6 enabled connecting to an IPv6 peer.
PAN-2286
=> PAN-2286 - quieter exceptions when network is unreachable

pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java, pantheon/src/main/java/tech/pegasys/pantheon/util/PermissioningConfigurationValidator.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java, pantheon/src/test/java/tech/pegasys/pantheon/util/LocalPermissioningConfigurationValidatorTest.java
To prevent unexpected behaviour, if a static node is not in the nodes whitelist
(when permissioning is enabled) pantheon will not start (rather than starting
with only whitelisted static nodes).
=> Fail at load if static nodes not whitelisted

docs/Tutorials/Azure/Azure-Private-Network-Quickstart.md
Url on the tutorial is pointing to my fork, forgot to make the change.
Once merge, we can remove the NicolasMassart:azure_deploy_button branch from my fork. My bad, sorry.
The links works the same for the moment, just using a JSON from the wrong place. So no visible issue for the users.
Quick fix
=> fix azure deploy url

ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/core/PendingTransactions.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/task/AbstractEthTask.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/fastsync/FastSyncValidationPolicyTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/netty/DeFramerTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyPeerConnectionTest.java, metrics/src/main/java/tech/pegasys/pantheon/metrics/noop/NoOpMetricsSystem.java, metrics/src/main/java/tech/pegasys/pantheon/metrics/prometheus/PrometheusMetricsSystem.java, metrics/src/test/java/tech/pegasys/pantheon/metrics/noop/NoOpMetricsSystemTest.java, metrics/src/test/java/tech/pegasys/pantheon/metrics/prometheus/PrometheusMetricsSystemTest.java, services/pipeline/src/test/java/tech/pegasys/pantheon/services/pipeline/PipelineBuilderTest.java
* Number of metrics labels need to match up with constructor
* Number of labels must be consistant, so I split it into two metrics
* Also, naming best practices say that sum() and avg() of a metric
should be meaningful, separating into two metrics fixes that.
* fix style issues (finals, intellij warnings)
=> Fix metrics breakages

config/src/main/java/tech/pegasys/pantheon/config/GenesisConfigOptions.java, config/src/main/java/tech/pegasys/pantheon/config/JsonGenesisConfigOptions.java, config/src/main/resources/dev.json, config/src/test-support/java/tech/pegasys/pantheon/config/StubGenesisConfigOptions.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/MainnetProtocolSpecs.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/ProtocolScheduleBuilder.java, ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/vm/VMReferenceTest.java
Make the contract size limit configurable in the genesis config, making it possible to override milestone based configurations in a private network.
=> Make contract size limit configurable.

ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/EthPeers.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/fastsync/FastSyncActions.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/EthPeersTest.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/fullsync/FullSyncChainDownloaderTest.java
Choose sync target based on td rather than height.
=> [PAN-2330] Choose sync target based on td rather than height

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/DeFramer.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/exceptions/BreachOfProtocolException.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/exceptions/PeerDisconnectedException.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/netty/DeFramerTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/netty/testhelpers/NettyMocks.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/netty/testhelpers/SubProtocolMock.java
This PR fixes a few issues where the `DeFramer` channel handler would forward messages down the netty pipeline before downstream channel handlers were set up.   
Previously, the `DeFramer` would only handle the initial `Hello` message, forwarding everything else down the pipeline.  It now checks for `Disconnect` messages and other invalid messages received before downstream handlers are set up.  
Additionally, we no longer return early from this handler in the case where a disconnect is sent.  There's some buffer time between sending a disconnect message and actually terminating a connection.  In that window of time, we could receive other messages from the peer which need to be handled.
=> [PAN-2433] Fix netty pipeline

build.gradle
There is one check that has issues in Java 12 and has yet to be fixed.
Disable it when we detect we are being built on Java 12.
PIE-1505
=> PIE-1505 - Build broken in Java 12

branch-from-tag.sh
I found this issue when testing the "Release: Branch from Tag" for EthSigner (formerly EthFirewall).
This allows the release from branch release job have a / in the branch name being used e.g. release/1.1
Due the use of / as separators in the regular expression to update the job name in the Jenkins.release currently it fails with error "number option to `s' command may not be zero" when using a branch name with a / in it. I've just changed the separator to be # instead of /.
=> Allow use of / in branch name when using the branch from tag release job

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/api/PeerConnection.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/peers/DefaultPeer.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/peers/StaticNodesParserTest.java, ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/SmartContractPermissioningController.java, util/src/main/java/tech/pegasys/pantheon/util/enode/EnodeURL.java
Keep `EnodeURL.nodeId` as a `BytesValue`.  Keeping all node ids consistently stored as `BytesValues` makes comparisons simpler and minimizes the need for type conversions.  For example, `Peer.getId()` and `EnodeURL.getNodeId()` can be more easily compared.
=> Keep enode nodeId stored as a BytesValue

ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/PendingTransactions.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionPool.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/PendingTransactionsTest.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionPoolTest.java
In an effort to make the change set inevitably necessitated by the acceptance criteria of `PAN-1339` less onerous, and consequently the review more palatable, I've decided to serialize it into constituent elements -- each of which constituting a relatively discrete semantic chunk.  
In order to disseminate local transactions to new peers we'll require a mechanism to fetch local transactions in isolation -- this is that mechanism (_along with associated test infrastructure_).
=> [MINOR / PAN-1339 (A)] Fetch local transactions in isolation

consensus/ibft/src/integration-test/java/tech/pegasys/pantheon/consensus/ibft/support/StubbedPeerConnection.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/IbftGossip.java, consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/network/ValidatorPeers.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/network/MockPeerFactory.java, consensus/ibft/src/test/java/tech/pegasys/pantheon/consensus/ibft/network/ValidatorPeersTest.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/EthPeer.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/MockPeerConnection.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/TestNodeList.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/results/PeerResult.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/AdminJsonRpcHttpServiceTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/MockPeerConnection.java, ethereum/mock-p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/testing/MockNetwork.java, ethereum/mock-p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/testing/MockNetworkTest.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/InsufficientPeersPermissioningProvider.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/api/PeerConnection.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryAgent.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/ApiHandler.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyP2PNetwork.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyPeerConnection.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/PeerConnectionRegistry.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/peers/PeerBlacklist.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/InsufficientPeersPermissioningProviderTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryAgentTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/netty/DeFramerTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyP2PNetworkTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/netty/PeerConnectionRegistryTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/peers/PeerBlacklistTest.java
Small cleanup to the PeerConnection interface:
- Keep local / remote addresses as `InetSocketAddress` values
- Add `getEnode` method, remove `isRemoteEnode` since this can be checked directly now
- Rename `getPeer` to `getPeerInfo`
=> [PAN-2560] Cleanup PeerConnection interface

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyP2PNetwork.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyP2PNetworkTest.java
Simplify Enode construction by using existing methods.
=> Simplify enode construction

ethereum/jsonrpc/src/integration-test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcTestMethodsFactory.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcMethodsFactory.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/NetServices.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/AbstractEthJsonRpcHttpServiceTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceHostWhitelistTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceLoginTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceRpcApisTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceTest.java, pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java
Implemented a JSON RPC method "net_services" that takes no input
parameter and returns an object
containing a list of enabled services (jsonrpc, p2p, ws, metrics) with
"host" and "port", as show below;
{
"id":1,
"jsonrpc": "2.0",
"result": {
"jsonrpc": {"host": "127.0.0.1", "port":3000},
"p2p":{"host": "127.0.0.1", "port":3000},
"ws":{"host": "127.0.0.1", "port":3000},
"metrics":{"host": "127.0.0.1", "port":3000}
}
}
In case a service is not enabled, that will not be included in the list;
{
"id":1,
"jsonrpc": "2.0",
"result": {}
}
**This PR includes all the changes requested by reviewer in the PR# 1269 (closed uncommitted)
=> PAN-2485#Add net_services json rpc endpoint

ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/core/Synchronizer.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/DefaultSynchronizer.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/PipelineChainDownloader.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/fastsync/FastSyncDownloader.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/fullsync/FullSyncDownloader.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/PipelineChainDownloaderTest.java, pantheon/src/main/java/tech/pegasys/pantheon/Runner.java
Stop the `Synchronizer` before stopping the `P2PNetwork` - otherwise when the network is stopped, all the tasks performed by `Synchronizer` fail causing it to think fast sync failed and switching to full sync.  The chain downloader had to ignore `CancellationException` to work around this but an explicit stop is much clearer.
https://pegasys1.atlassian.net/browse/PAN-2535
=> Stop synchronizer prior to stopping the network

ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/NetServices.java
It turns out we don't have the p2p host and port at RPC initialization.
To fix this change to query hosts and ports at method invocaiton time
instead of when the constructor is called.
fixes PAN-2577
=> PAN-2577 - missing p2p info when queried live

ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcMethodsFactory.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/results/PendingTransactionsStatisticsResult.java
The txpool_pantheonStatistics json rpc was not enabled.
This PR adds it to the txpool group and ensures that it is active at appropriate times.
=> Ensured that the transaction statistics endpoint is exposed.

ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/NetServices.java
It turns out we don't have the p2p host and port at RPC initialization.
To fix this change to query hosts and ports at method invocaiton time
instead of whent he constructor is called.
(cherry picked from commit 105dc5b51e50c8dff7f9af9bcb7c29312c5a6dbd, #1310)
PAN-2580
=> PAN-2580 - missing p2p info when queried live 

acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ThreadPantheonNodeRunner.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/PantheonControllerBuilder.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
Seems like a mistake, we named it as `rocksdDbConfiguration`, but shouldn't it be `rocksDbConfiguration`?
=> [MINOR] Rename rocksdDbConfiguration to rocksDbConfiguration

ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/MockPeerConnection.java, ethereum/mock-p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/testing/MockNetwork.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/api/PeerConnection.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/DefaultP2PNetwork.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/exceptions/UnexpectedPeerConnectionException.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/netty/AbstractHandshakeHandler.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/netty/DeFramer.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/netty/HandshakeHandlerInbound.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/netty/HandshakeHandlerOutbound.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/netty/NettyPeerConnection.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/network/netty/DeFramerTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/network/netty/NettyPeerConnectionTest.java
Add method `PeerConnection.getPeer()` to make it easier to consolidate API's around the `Peer` representation.  This PR also adds a check to make sure that the peer we attempt to connect to matches the peer info we receive once the connection is established.
=> [PAN-2605] Add getPeer method to PeerConnection

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/netty/DeFramer.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/peers/Peer.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/wire/PeerInfo.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/network/netty/DeFramerTest.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/DefaultCommandValues.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java, util/src/main/java/tech/pegasys/pantheon/util/enode/EnodeURL.java
It is common for peers to advertise a listening port of 0.  Handle this case by using a default listening port of 30303.
=> Handle case where peers advertise a listening port of 0

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/netty/DeFramer.java
Add explanatory comment on the choice of the default port in `DeFramer`.  Original discussion here: https://github.com/PegaSysEng/pantheon/pull/1391#discussion_r280479459
=> Add explanatory comment about default port

ethereum/core/build.gradle
Resolves path issues with running on Windows. 
At the moment it seems we aren't evaluating `VMTests`, `TrieTests`, or `TransitionTests` -- why is that?
[![enter image description here][1]][1]
[1]: https://i.stack.imgur.com/CVmCy.png
=> [PAN-2586] Reference tests fail on Windows

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/DefaultP2PNetwork.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/network/DefaultP2PNetworkTest.java
Start listening for incoming p2p connections only after start() is invoked.  Additionally, since we're no longer setting up listening in the constructor, we can now gate the stop() method so that it only runs after the network has been started.
=> [PAN-2624] Start listening for p2p connections after start() is invoked

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/DefaultP2PNetwork.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/network/DefaultP2PNetworkTest.java
This PR reworks handling of potentially null / empty values in `DefaultP2PNetwork`.  `PeerInfo` is wrapped in an `Optional` to make it more obvious that this value may be empty.  Some additional checks have been added to shortcut operations that should only execute when the network is fully up and running: 
- Peers are not permitted to connect until the network is fully up
- `connect()` will return an exceptional result if invoked before the network is up
=> Fix p2p PeerInfo handling

acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/ClusterThreadNodeRunnerAcceptanceTest.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/cluster/Cluster.java
To make sure it is automated I extended the cluster to accept a defined
PantheonNode instead of an automatic one (where automatic is the
default) and then cloned a simple test and forced it to use the
ThreadPantheonNodeRunner.
PAN-2634
=> [PAN-2634] Make sure ThreadPantheonNodeRunner is exercised by automation

ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionPool.java
The transaction pool doesn't add remote transactions until we're in sync. Previously this check was performed after sorting and beginning to iterate the transactions.  Move the check to the very start of the method so we bail out as soon as possible.
Additionally, since we no longer reject transactions where the nonce is too high, we don't need to sort the transactions by nonce.
=> Optimise TransactionPool.addRemoteTransaction

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/DefaultP2PNetwork.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/peers/MaintainedPeers.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/network/DefaultP2PNetworkTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/network/P2PNetworkTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/peers/MaintainedPeersTest.java
Move peer maintenance list management into a new `MaintainedPeers` class.  This change will help facilitate the break up of logic within `DefaultP2PNetwork` by decoupling the add / remove action from the handling of peers in this list.  
This change also makes tests more robust by exposing a public dependency that can be checked directly, rather than having to reach into the `DefaultP2PNetwork` to check a private field.  Some connection-related checks were moved into `DefaultP2PNetwork.connect` in order to reduce the amount of custom logic executed when a new peer is added to `MaintainedPeers`.
=> [PAN-2730] Create MaintainedPeers class

ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/AccountLocalConfigPermissioningController.java, ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/AccountLocalConfigPermissioningControllerTest.java, pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java
Added metrics for local transaction permissioning.
fixes #PIE-1578
=> [PIE-1578] added local transaction permissioning metrics

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/FindNeighborsPacketData.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/NeighborsPacketData.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PingPacketData.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PongPacketData.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/rlpx/wire/PeerInfo.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/FindNeighborsPacketDataTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/NeighborsPacketDataTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PingPacketDataTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PongPacketDataTest.java, ethereum/rlp/src/main/java/tech/pegasys/pantheon/ethereum/rlp/AbstractRLPInput.java, ethereum/rlp/src/main/java/tech/pegasys/pantheon/ethereum/rlp/RLPInput.java, ethereum/rlp/src/test/java/tech/pegasys/pantheon/ethereum/rlp/BytesValueRLPInputTest.java
[EIP-8](https://eips.ethereum.org/EIPS/eip-8) specifies that devp2p discovery message deserialization should be lenient in order to make protocol upgrades easier.  This PR updates discovery packet deserialization to be more lenient by:
* ignoring extra fields
* ignoring the version in PING packets
=> [PAN-2811] Be more lenient with discovery message deserialization

docs/Getting-Started/Starting-Pantheon.md, docs/Monitoring/Alethio/Lite-Block-Explorer.md, docs/Pantheon-API/Pantheon-API.md, docs/Privacy/Configuring-Privacy.md, docs/Reference/Pantheon-CLI-Syntax.md, docs/Tutorials/Create-IBFT-Network.md, docs/Tutorials/Create-Permissioned-Network.md, docs/Tutorials/Create-Private-Clique-Network.md, docs/Tutorials/Create-Private-Network.md
add quotes around asterisks params to prevent shell expansion so `--option=*` is now `--option="*"` 
fixes PAN-2766
=> add quotes around asterisks params to prevent shell expansion

Jenkinsfile.smoke
Modified the Jenkins Smoke Test to use private docker images for Zulu OpenJDK (8, 11 & 12) and OpenJDK 12
=> [PIE-1647] Update smoke tests docker images for zulu and openjdk to private ones

ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/privacy/PrivateTransactionHandler.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcMethodsFactory.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/privacy/EeaGetTransactionCount.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/privacy/EeaGetTransactionCountTest.java
Have the eeaTransactionCount json RPC reuse the nonce calculator stored in the PrivateTransactionHandler.
Potentially this function should be pushed down to the worldStateArchive ...
=> Remove duplication between EeaTransactionCountRpc & PrivateTransactionHandler

acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/PantheonNode.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ProcessPantheonNodeRunner.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ThreadPantheonNodeRunner.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/configuration/PantheonFactoryConfiguration.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/configuration/PantheonFactoryConfigurationBuilder.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/configuration/PantheonNodeFactory.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/configuration/privacy/PrivacyPantheonFactoryConfiguration.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/configuration/privacy/PrivacyPantheonFactoryConfigurationBuilder.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/configuration/privacy/PrivacyPantheonNodeFactory.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/privacy/PrivacyNode.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/config/NetworkingConfiguration.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/DefaultP2PNetwork.java, pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/options/NetworkingOptions.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/options/NetworkingOptionsTest.java
Try to cut down on intermittent acceptance tests failures by retrying connections more frequently during acceptance tests:
* Add experimental option for setting the frequency of network checks
* Use these experimental options to modify acceptance test configuration
=> [PAN-2797] Check connections more frequently during acceptance tests

pantheon/src/main/java/tech/pegasys/pantheon/cli/util/ConfigOptionSearchAndRunHandler.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/util/ConfigOptionSearchAndRunHandlerTest.java
The environment variable config handler was not used unless a config file was specified.  This fixes that so it is always used and simplifies the code to make this kind of error much less likely in the future.
=> Read config from env vars when no config file specified

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/config/RlpxConfiguration.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/DefaultP2PNetwork.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/peers/DefaultPeerPrivileges.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/peers/PeerPrivileges.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/rlpx/RlpxAgent.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/config/RlpxConfigurationTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/peers/MaintainedPeersTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/rlpx/RlpxAgentTest.java
This PR makes static nodes exempt from the max remote connections limit.  
Some other small changes include:
* Renaming `PeerProperties` to `PeerPrivileges`
* Reordering some of the fields in `RlpxAgent`
* Additional tests
=> [PAN-1683] Exempt static nodes from all connection limits

acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/PantheonNode.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ThreadPantheonNodeRunner.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/configuration/PantheonFactoryConfigurationBuilder.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/TestNode.java, ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/config/RlpxConfiguration.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/config/RlpxConfigurationTest.java, ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/rlpx/RlpxAgentTest.java, pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java, pantheon/src/test/java/tech/pegasys/pantheon/RunnerTest.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java, pantheon/src/test/resources/everything_config.toml
Rework remote connection limit defaults:
* Enable remote connection limits by default
* Bump up the default percentage of remote connection to 60 in order to make the limit a little more forgiving for private networks where all nodes may use the same configuration
Other changes include:
- Change flag from `--remote-connections-percentage` to `--max-remote-connections-percentage` for clarity
- Reword help text for clarity / consistency
- Use `float` to represent max percentage of remote connection consistently
- Remove extraneous configuration of these options in tests
=> [PAN-1683] Rework remote connection limit flag defaults

ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/MainnetEvmRegistries.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/MainnetProtocolSpecs.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/vm/operations/SStoreOperation.java, ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/vm/operations/SStoreOperationTest.java
Add minimum remaining gas check to exceptional halt reasons.  Configure it
to zero pre-istanbul and 2300 for istanbul.
=> [PAN-2905] EIP-1706 - Disable SSTORE with gasleft lt call stipend 

pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java, pantheon/src/test/resources/everything_config.toml
Rename CLI flag from `--max-remote-connections-percentage` to `--remote-connections-max-percentage`, so that this flag will show up next to the related flag `--remote-connections-limit-enabled` when help is displayed.
=> [PAN-1683] Rename CLI flag for better ordering of options

ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/chain/ChainHead.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/chain/DefaultMutableBlockchain.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/ChainState.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/EthPeers.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/fullsync/BetterSyncTargetEvaluator.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/fullsync/FullSyncTargetManager.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/state/SyncState.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/state/SyncTarget.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/ChainStateTest.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/state/SyncStateTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/AdminNodeInfoTest.java
When performing "in-sync" checks, test against the sync target and our best peer.  This handles cases where the sync target is temporarily empty, but we are not yet in sync.
Also, consolidate logic to determine whether a peer's chain is "better" than our chain and add tests.
=> [PAN-2917] Rework "in-sync" checks

ethereum/blockcreation/src/main/java/tech/pegasys/pantheon/ethereum/blockcreation/MiningCoordinator.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/EthHashrate.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/EthHashrateTest.java
Ethstats reporting was still failing on Clique based networks because our `eth_hashrate` call returned an error when the `MiningCoordinator` doesn't support hash rates.  The standard behaviour is to return 0 in this case, so adjust Pantheon to match.
=> Report 0 hashrate when the mining coordinator doesn't support mining

ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/MainnetProtocolSpecs.java
When a chainID is not specified in a genesis file for the purposes of the chained
opcode we interpret that to mean chain ID 0.
=> [PAN-2903] no chain ID means Chain ID opcode returns 0

ethereum/blockcreation/src/main/java/tech/pegasys/pantheon/ethereum/blockcreation/EthHashBlockCreator.java, ethereum/blockcreation/src/test/java/tech/pegasys/pantheon/ethereum/blockcreation/EthHashBlockCreatorTest.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/headervalidationrules/ProofOfWorkValidationRule.java, ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/mainnet/headervalidationrules/ProofOfWorkValidationRuleTest.java, util/src/main/java/tech/pegasys/pantheon/util/uint/UInt256.java
If you try and do a difficulty of 1 the UInt256 class used for comparison throws
an error because 2^256 is 33 bytes.  Instead use 2^256-1 which is 32 bytes.
=> [PAN-2954] - Allow fixedDifficulty=1 to mean "all solutions"

docs/Configuring-Pantheon/Using-Configuration-File.md, docs/Deploying-Pantheon/Migration-Docker.md, docs/Getting-Started/Run-Docker-Image.md, docs/Permissions/Onchain-Permissioning/Getting-Started-Onchain-Permissioning.md, docs/Permissions/Onchain-Permissioning/Onchain-Permissioning.md, docs/Permissions/Onchain-Permissioning/Production.md, docs/Privacy/Explanation/Privacy-Groups.md, docs/Privacy/Explanation/Privacy-Overview.md, docs/Privacy/Explanation/Private-Transaction-Processing.md, docs/Privacy/How-To/Access-Private-Transactions.md, docs/Privacy/How-To/Create-Manage-Privacy-Groups.md, docs/Privacy/How-To/Creating-Sending-Private-Transactions.md, docs/Privacy/How-To/EEA-Compliant.md, docs/Privacy/How-To/Pantheon-Privacy.md, docs/Privacy/How-To/eeajs.md, docs/Reference/Pantheon-API-Methods.md, docs/Reference/web3js-eea-Methods.md, docs/Using-Pantheon/Transactions/Revert-Reason.md, mkdocs.yml
Bunch of docs changes for the release-1.2 branch:
#1754 
#1650 
#1774 
#1773 
#1771 
#1769 
#1765
#1779 
#1781 
#1787 
#1788
#1790
#1792
=> Bunch of docs changes for the release-1.2 branch

ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/core/AbstractWorldUpdater.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/core/Account.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/core/AccountState.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/core/WorldState.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/worldstate/DefaultMutableWorldState.java, ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/worldstate/DefaultMutableWorldStateTest.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/DebugAccountRange.java
Accounts streamed directly from the world state trie may be missing an address value.  Create a special type `StreamableAccount` to make explicit the fact that this value may be missing.
=> [PAN-2995] Make explicit that streamed accounts may be missing their address

services/tasks/src/main/java/tech/pegasys/pantheon/services/tasks/FlatFileTaskCollection.java, services/tasks/src/test/java/tech/pegasys/pantheon/services/tasks/FlatFileTaskCollectionTest.java
Windows has some slightly different Java NIO semantics, regarding size
after writing and whether files are deleted on close (they are not immediately deleted).
The first issue is we shouldn't be using Integer.SIZE when we mean
Integer.BYTES.  Integer.SIZE is bit count, BYTES is byte count.
The second issue is we cannot count on these work files showing up or
being deleted from the file system consistently across platforms.  The
ordering is consistent within platforms but not across.  The test was
re-written to check the read and write file numbers instead.
=> [PAN-2900] Fix FlatFileTaskCollection tests

metrics/core/src/main/java/tech/pegasys/pantheon/metrics/prometheus/MetricsConfiguration.java, metrics/core/src/main/java/tech/pegasys/pantheon/metrics/prometheus/PrometheusMetricsSystem.java, metrics/core/src/test/java/tech/pegasys/pantheon/metrics/prometheus/PrometheusMetricsSystemTest.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/options/MetricsCLIOptions.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/options/MetricsCLIOptionsTest.java
Add an experimental flag for disabling metrics timers: `--Xmetrics-timers-enabled=<boolean>`
=> [PIE-1846] Add an experimental flag for disabling timers

config/src/main/java/tech/pegasys/pantheon/config/GenesisConfigFile.java, config/src/test/java/tech/pegasys/pantheon/config/GenesisConfigFileTest.java
The technique is to parse with comments disabled, and if a parse exception is
detected re-parse with comments allowed, and if successful complain at warn.
To turn this option off we just unwrap the try and delete the catch and update
the test.
=> [PAN-3012] Print warning when there are comments in genesis file

pantheon/src/main/java/tech/pegasys/pantheon/chainimport/internal/BlockData.java, pantheon/src/main/java/tech/pegasys/pantheon/chainimport/internal/ChainData.java, pantheon/src/main/java/tech/pegasys/pantheon/chainimport/internal/TransactionData.java, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/clique/blocks-import-invalid-bad-parent.json, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/clique/blocks-import-invalid-bad-tx.json, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/clique/blocks-import-special-fields.json, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/clique/blocks-import-valid-addendum.json, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/clique/blocks-import-valid-no-block-identifiers.json, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/clique/blocks-import-valid.json, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/ethash/blocks-import-invalid-bad-parent.json, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/ethash/blocks-import-invalid-bad-tx.json, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/ethash/blocks-import-special-fields.json, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/ethash/blocks-import-valid-addendum.json, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/ethash/blocks-import-valid-no-block-identifiers.json, pantheon/src/test/resources/tech/pegasys/pantheon/chainimport/ethash/blocks-import-valid.json, testutil/src/main/resources/fork-chain-data/src/common-blocks.json, testutil/src/main/resources/fork-chain-data/src/fork-blocks.json
This PR makes a few small changes to the JSON import format:
* Allow "comment" fields for documentation
* Use "secretKey" as the field name for private keys to match the reference test json format
=> [PIE-1804] Tweak JSON import format

ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/AbstractJsonRpcHttpBySpecTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/DebugJsonRpcHttpBySpecTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/EthJsonRpcHttpBySpecTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/TraceJsonRpcHttpBySpecTest.java
Simplify JSON-RPC spec test setup by walking resource directories to search for spec files rather than explicitly including every single spec file.
=> [PIE-1805] Simplify json rpc spec test setup

ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/AdminChangeLogLevel.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/AdminChangeLogLevelTest.java
Provide a way to enable logging for specific packages or classes. e.g. if my node isn't discovering peers I may want to see peer discovery at TRACE level but keep the Synchronizer at INFO level.
```json
{  
"jsonrpc":"2.0",
"method":"admin_changeLogLevel",
"params":[  
"DEBUG",
[  
"tech.pegasys.pantheon.ethereum.eth.manager",
"tech.pegasys.pantheon.ethereum.p2p.rlpx.connections.netty.ApiHandler"
]
],
"id":1
}
```
```json
{
"jsonrpc": "2.0",
"id": 1,
"result": "Success"
}
```
=> [PAN-2331] Finer grained logging configuration

config/src/main/java/tech/pegasys/pantheon/config/GenesisConfigFile.java, config/src/main/java/tech/pegasys/pantheon/config/JsonGenesisConfigOptions.java, config/src/test/java/tech/pegasys/pantheon/config/GenesisConfigFileTest.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/CliquePantheonControllerBuilder.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/IbftLegacyPantheonControllerBuilder.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/IbftPantheonControllerBuilder.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/MainnetPantheonControllerBuilder.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/PantheonController.java, pantheon/src/main/java/tech/pegasys/pantheon/controller/PantheonControllerBuilder.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java, pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
Add a generalized genesis config override facility for command line use.  Only useful for string or integer config values, not object values.
Sample use - enable Istanbul fork on block 99 million
`--override-genesis-config=istanbulFork=99000000`
Overriding a value with an empty string unsets the value
Sample use - disable Istanbul fork by un-setting `istanbulFork`: 
`--override-genesis-config=istanbulFork=`
=> [PAN-3126] add an override facility for genesis configs

acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/MetricsAcceptanceTest.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/PantheonNode.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ProcessPantheonNodeRunner.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ThreadPantheonNodeRunner.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/configuration/PantheonNodeConfigurationBuilder.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/NetServices.java, metrics/core/src/main/java/tech/pegasys/pantheon/metrics/prometheus/MetricsConfiguration.java, metrics/core/src/main/java/tech/pegasys/pantheon/metrics/prometheus/MetricsHttpService.java, pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
Remove metrics from registration.  Doing it this way here always results in a
NoOpsMetrics being inited because CLI options have not been parsed.
=> [PIE-1859] - remove metrics from plugin registration
