.github/issue_template.md, CLA.md, CONTRIBUTING.md, docs/architecture/java-modules.md, docs/community/code-reviews.md, docs/community/community-membership.md
- Created CLA.md
- Updated Gitter URLs
- Updated Role definitions
- deleted java-modules.md.  If written, it belongs in the JavaDoc package.hmtl
- Removed broken index link to Documentation Style Guide
- Fixed broken link to PR labels
- updated issue template to comment each line individually.
=> Cleaned up outstanding TODOs in documentation

ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyP2PNetwork.java
Check that P2P network is successfully initialized and throw an explicit exception on failure.
=> Add better handling for port conflict error

ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryAgentTest.java
Temporarily disable intermittently failing test while we work on a fix.
=> Ignore flaky test

ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/WorldStateDownloader.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/WorldStateDownloaderTest.java
Update `WorldStateDownloader.run()` interface as discussed here: https://github.com/PegaSysEng/pantheon/pull/658#discussion_r250859283
=> [NC-2208] Update WorldStateDownloader run() interface to accept header

ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/AccountTrieNodeDataRequest.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/CodeNodeDataRequest.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/NodeDataRequest.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/RequestType.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/StorageTrieNodeDataRequest.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/TrieNodeDataRequest.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/NodeDataRequestTest.java
Add serialization functionality to NodeDataRequest
=> Add serialization functionality to NodeDataRequest

CONTRIBUTING.md
Fixed the "Good First Issue" Link in "Your First Code Contribution" section of /CONTRIBUTING.md 
fixes #797
=> [797] "Good First Issue" Link is Broken in CONTRIBUTING.md

ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
=> Remove unnecessary sleep

pantheon/src/main/java/tech/pegasys/pantheon/controller/IbftPantheonController.java
Expose the IBFT mining co-ordinator so that RPCs which require this will work with IBFT.
=> Expose the Ibft MiningCoordinator

docs/custom_theme/partials/footer.html, mkdocs.yml
add a link to the issue system (jira) in the doc site footer
PIE-1485
=> add link to issues system to the doc site footer

docs/EthStats/Lite-Block-Explorer.md
we did a rename/rebrand of the lite explorer, this pr updates names and links
thank you
=> rename of ethstats lite explorer to ethereum lite explorer

docs/Reference/Pantheon-CLI-Syntax.md
Remove unstable fast sync note in documentation as fast sync is now usable publicly 🚀 
fixes PAN-2525 doc part
=> Remove unstable fast sync note in documentation

CHANGELOG.md, docs/Permissions/Onchain-Permissioning.md
Backport Changelog and RPC change
=> Backport Changelog and RPC change

acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/web3j/privacy/DeployPrivateSmartContractAcceptanceTest.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/Subscription.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/SubscriptionBuilder.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/blockheaders/NewBlockHeadersSubscription.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/logs/LogsSubscription.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/pending/PendingTransactionDetailResult.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/pending/PendingTransactionSubscriptionService.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/request/SubscriptionParam.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/request/SubscriptionRequestMapper.java, ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/syncing/SyncingSubscription.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/SimpleTestTransactionBuilder.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/SubscriptionBuilderTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/pending/PendingTransactionDroppedSubscriptionServiceTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/pending/PendingTransactionSubscriptionServiceTest.java, ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/request/SubscriptionRequestMapperTest.java
Support including the transaction details in the pending transactions query.
=> Include transaction details when subscribed to Pending transactions

docs/Configuring-Pantheon/FreeGas.md
Updated block size limit configuration
=> Updated block size limit configuration

acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/ClusterNoDiscoveryAcceptanceTest.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/ClusterThreadNodeRunnerAcceptanceTest.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/P2pDisabledAcceptanceTest.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/jsonrpc/Clique.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/NodeConfiguration.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/PantheonNode.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ProcessPantheonNodeRunner.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ThreadPantheonNodeRunner.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/cluster/Cluster.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/cluster/ClusterConfigurationBuilder.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PantheonFactoryConfigurationBuilder.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PantheonNodeFactory.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PermissionedNodeBuilder.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/pubsub/WebSocketConnection.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/jsonrpc/HttpServiceLoginAcceptanceTest.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/jsonrpc/admin/AdminAddPeerAcceptanceTest.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/LocalConfigNodePermissioningAcceptanceTest.java, acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/NodeSmartContractNodePermissioningAcceptanceTestBase.java
Clean up Acceptance tests to follow our coding conventions
For builders, don't use get/set for properites.
Otherwise use get/set
=> Acceptance Test Cleanup

docs/Getting-Started/Run-Docker-Image.md, docs/Pantheon-API/GraphQL.md, docs/Reference/Pantheon-CLI-Syntax.md
=> Added Graphql options

docs/Alethio/Lite-Block-Explorer.md, docs/Alethio/Lite-Network-Monitor.md, docs/Alethio/Overview.md
- update Network monitor name to EthStats Lite as it's the correct branding
- fixed [WebSocket](https://en.wikipedia.org/wiki/WebSocket) case
fixes PIE-1656
=> Update ethstats doc

CHANGELOG.md
Added 1.1.3 changes to changelog
=> Added 1.1.3 changes to changelog

services/kvstore/src/main/java/tech/pegasys/pantheon/services/kvstore/ColumnarRocksDbKeyValueStorage.java, services/kvstore/src/main/java/tech/pegasys/pantheon/services/kvstore/MonitorableKeyValueStorage.java, services/kvstore/src/main/java/tech/pegasys/pantheon/services/kvstore/RocksDBMetricsHelper.java, services/kvstore/src/main/java/tech/pegasys/pantheon/services/kvstore/RocksDbKeyValueStorage.java
- introduce `RocksDBMetricsHelper `
- factorise code
- remove metrics instanciation in `RocksDbKeyValueStorage` and `ColumnarRocksDbKeyValueStorage`
=> Factorise metrics code for KeyValueStorage database

ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/fastsync/FastSyncActions.java, ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/fastsync/FastSyncError.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/fastsync/FastSyncActionsTest.java, ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/fastsync/FastSyncDownloaderTest.java
Instead of aborting fast sync when our peers lack sufficient height, just wait for more peers to join.
=> [PIE-1780] Wait and retry if best peer's chain is too short for fast sync

docker/Dockerfile
Bringing https://github.com/PegaSysEng/pantheon/pull/1782 into the release
=> update defaults host interfaces (#1782)

ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/MainnetEvmRegistries.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/MainnetPrecompiledContractRegistries.java, ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/MainnetProtocolSpecs.java
Revise Istanbul versioning assignments so all changes are in version zero.
This does not remove support for EIP-1702.
=> [PAN-2829] Revise Istanbul Versioning asisgnemnts

ROADMAP.md
Updates the roadmap for the 1.2 release. Should be backported to the RC branch.
=> Update Roadmap for 1.2 Release

docs/Monitoring/Alethio/Lite-Block-Explorer.md
Update the localhost link to include port number.
=> Update localhost link to include port number.

ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/precompiles/AltBN128MulPrecompiledContract.java
correct Istanbul ECMUL gas cost to 6k gas.
=> [PAN-2904] EIP-1108 - Reprice alt_bn128 

ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/AbstractJsonRpcHttpBySpecTest.java, ethereum/jsonrpc/src/test/resources/tech/pegasys/pantheon/ethereum/jsonrpc/trace/trace_replayBlockTransactions_0x0.json, ethereum/jsonrpc/src/test/resources/tech/pegasys/pantheon/ethereum/jsonrpc/trace/trace_replayBlockTransactions_0x1.json, ethereum/jsonrpc/src/test/resources/tech/pegasys/pantheon/ethereum/jsonrpc/trace/trace_replayBlockTransactions_earliest.json, ethereum/jsonrpc/src/test/resources/tech/pegasys/pantheon/ethereum/jsonrpc/trace/trace_replayBlockTransactions_invalidBlockParam.json, ethereum/jsonrpc/src/test/resources/tech/pegasys/pantheon/ethereum/jsonrpc/trace/trace_replayBlockTransactions_invalidTraceOptions.json, ethereum/jsonrpc/src/test/resources/tech/pegasys/pantheon/ethereum/jsonrpc/trace/trace_replayBlockTransactions_pending.json
Temporary ignore tracing API tests.
Tests will be enabled again when https://github.com/PegaSysEng/pantheon/pull/1886 will be merged.
=> Ignore flaky tracing tests

plugin-api/build.gradle
* fix missing dot
* remove unused import
* remove empty dependencies
=> update plugins-api build script

acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/web3j/privacy/EnclaveErrorAcceptanceTest.java
Verifies that a transaction fails if a participant in a private transaction is offline.
=> verify private transaction fails if participant is offline

ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/vm/operations/SStoreOperation.java
When gas remaining is exactly 2300 we should also fail.
=> [PAN-2905] Handle exact value correctly
